define([
  'ember',
  'packages/platform/data',
  './lib/namespace',

  './lib/filter_serialization',

  './lib/data_stores/ad_hoc_store',
  './lib/data_stores/mobile_device_store',
  './lib/data_stores/mobile_device_item_store',
  './lib/data_stores/mobile_device_group_store',
  './lib/data_stores/mobile_device_from_mobile_policy_store',
  './lib/data_stores/mobile_device_from_content_store',
  './lib/data_stores/mobile_device_installed_application_store',
  './lib/data_stores/mobile_device_installed_configuration_profile_store',
  './lib/data_stores/mobile_device_installed_provisioning_profile_store',
  './lib/data_stores/mobile_device_assigned_apps_store',
  './lib/data_stores/mobile_device_assigned_in_house_apps_store',
  './lib/data_stores/mobile_device_assigned_profiles_store',
  './lib/data_stores/mobile_device_performed_actions_store',

  './lib/data_stores/mobile_device_administrator_store',
  './lib/data_stores/mobile_device_certificate_store',
  './lib/data_stores/mobile_device_custom_field_store',
  './lib/data_stores/mobile_device_user_store',
  './lib/data_stores/mobile_policy_store',
  './lib/data_stores/mobile_policy_from_content_store',
  './lib/data_stores/mobile_policy_from_mobile_device_store',
  './lib/data_stores/mobile_policy_from_action_store',
  './lib/data_stores/content_store',
  './lib/data_stores/content_from_mobile_policy_store',
  './lib/data_stores/content_from_mobile_device_store',
  './lib/data_stores/in_house_application_store',
  './lib/data_stores/third_party_application_store',
  './lib/data_stores/in_house_application_from_policy_store',
  './lib/data_stores/third_party_application_from_policy_store',
  './lib/data_stores/configuration_profile_store',
  './lib/data_stores/configuration_profile_from_policy_store',
  './lib/data_stores/provisioning_profile_store',
  './lib/data_stores/actions_store',
  './lib/data_stores/actions_from_policy_store',
  './lib/data_stores/action_wallpaper_store',

  './lib/data_stores/vpp_accounts_store',

  './lib/data_stores/custom_field_store',
  './lib/data_stores/custom_field_data_type_store',
  './lib/data_stores/custom_field_format_as_store',
  './lib/data_stores/custom_field_enum_store',

  './lib/data_stores/command_mobile_history_store',
  './lib/data_stores/command_mobile_queue_store',
  './lib/data_stores/command_computer_history_store',
  './lib/data_stores/command_computer_queue_store',
  './lib/data_stores/command_computer_detail_store',
  './lib/data_stores/command_group_store',

  './lib/data_stores/user_prefs_store',
  './lib/data_stores/assignable_item_menu_store',
  './lib/data_stores/book_store',
  './lib/data_stores/smart_policy_store',

  './lib/data_stores/computer_list_store',
  './lib/data_stores/computer_group_store',
  './lib/data_stores/computer_item_memory_store',
  './lib/data_stores/computer_item_agent_information_store',
  './lib/data_stores/computer_item_hardware_store',
  './lib/data_stores/computer_item_system_software_store',
  './lib/data_stores/computer_item_cpu_store',
  './lib/data_stores/computer_item_volume_store_pc',
  './lib/data_stores/computer_item_volume_store_mac',
  './lib/data_stores/computer_item_network_adapter_store',
  './lib/data_stores/computer_item_missing_patch_pc_store',
  './lib/data_stores/computer_item_missing_patch_mac_store',
  './lib/data_stores/computer_item_installed_software_pc_store',
  './lib/data_stores/computer_item_installed_software_mac_store',
  './lib/data_stores/computer_item_installed_profile_store',

  './lib/data_stores/user_self_help_device_list_store',
  './lib/data_stores/user_self_help_location_accuracy_store',
  './lib/data_stores/user_self_help_tracking_interval_period_store',
  './lib/data_stores/user_self_help_privileges_store',

  './lib/actions/mobile_device_clear_passcode_action',
  './lib/actions/mobile_device_lock_action',
  './lib/actions/mobile_device_remote_erase_action',
  './lib/actions/mobile_device_send_message_action',
  './lib/actions/mobile_device_set_roaming_options_action',
  './lib/actions/mobile_device_set_ownership_action',
  './lib/actions/mobile_device_set_enrollment_user_action',
  './lib/actions/mobile_device_set_device_name_action',
  './lib/actions/mobile_device_set_organization_info_action',
  './lib/actions/mobile_device_retry_all_failed_profiles_action',
  './lib/actions/mobile_device_retry_all_failed_apps_action',
  './lib/actions/mobile_device_retry_all_tocken_action',
  './lib/actions/mobile_device_set_activation_lock_options_action',
  './lib/actions/mobile_device_change_application_configuration_action',

  './lib/actions/mobile_device_update_info_action',
  './lib/actions/mobile_device_install_application_action',
  './lib/actions/mobile_device_uninstall_application_action',
  './lib/actions/mobile_device_install_configuration_profile_action',
  './lib/actions/mobile_device_install_provisioning_profile_action',
  './lib/actions/mobile_device_uninstall_configuration_profile_action',
  './lib/actions/mobile_device_uninstall_provisioning_profile_action',
  './lib/actions/mobile_device_related_custom_field_data_delete_action',
  './lib/actions/mobile_device_related_custom_field_data_update_action',
  './lib/actions/mobile_device_related_performed_action_remove_action',
  './lib/actions/mobile_device_related_performed_action_reapply_action',

  './lib/actions/custom_field_delete_action',
  './lib/actions/custom_field_update_action',

  './lib/actions/mobile_policy_to_content_map_action_data',
  './lib/actions/mobile_policy_to_content_map_create_action',
  './lib/actions/mobile_policy_to_content_map_delete_action',

  './lib/actions/mobile_policy_to_mobile_device_map_create_action',
  './lib/actions/mobile_policy_to_mobile_device_map_delete_action',
  './lib/actions/mobile_policy_create_new_policy_action',
  './lib/actions/mobile_policy_create_new_smart_policy_action',
  './lib/actions/mobile_policy_update_smart_policy_action',
  './lib/actions/mobile_policy_delete_policy_action',
  './lib/actions/mobile_policy_rename_policy_action',
  './lib/actions/mobile_policy_add_configuration_profile_action',
  './lib/actions/mobile_policy_remove_configuration_profile_action',
  './lib/actions/mobile_policy_add_in_house_app_action',
  './lib/actions/mobile_policy_remove_in_house_app_action',
  './lib/actions/mobile_policy_add_third_party_app_action',
  './lib/actions/mobile_policy_remove_third_party_app_action',
  './lib/actions/mobile_policy_reexecute_action',

  './lib/actions/content_action_data',
  './lib/actions/content_create_batch_action',
  './lib/actions/content_update_action',
  './lib/actions/content_delete_action',
  './lib/actions/update_user_prefs_action',

  './lib/actions/mobile_command_history_delete_action',
  './lib/actions/mobile_command_queue_delete_action',
  './lib/actions/computer_command_history_delete_action',
  './lib/actions/computer_command_queue_delete_action',

  './lib/actions/computer_send_message_action',
  './lib/actions/computer_gather_inventory_action',

  './lib/actions/user_self_help_device_item_lock_action',
  './lib/actions/user_self_help_device_item_remote_erase_action',
  './lib/actions/user_self_help_device_item_reset_tracking_passcode_action',
  './lib/actions/user_self_help_device_item_track_device_action',
  './lib/actions/user_self_help_item_send_message_action',
  './lib/actions/user_self_help_device_item_clear_or_set_passcode_action',

  './lib/actions/action_add_update_action',
  './lib/actions/action_delete_action',
  './lib/actions/action_add_update_policy_assignment_action',
  './lib/actions/action_delete_policy_assignment_action',

  './lib/models/content',

  './lib/specs/content_spec',
  './lib/specs/content_from_mobile_policy_spec',
  './lib/specs/content_from_mobile_device_spec',
  './lib/specs/mobile_device_spec',
  './lib/specs/mobile_device_group_spec',
  './lib/specs/mobile_device_from_mobile_policy_spec',
  './lib/specs/mobile_device_from_mobile_content_spec',
  './lib/specs/mobile_device_installed_application_spec',
  './lib/specs/mobile_device_installed_config_profile_spec',
  './lib/specs/mobile_device_installed_provisioning_profile_spec',
  './lib/specs/mobile_device_assigned_apps_spec',
  './lib/specs/mobile_device_assigned_in_house_apps_spec',
  './lib/specs/mobile_device_assigned_profiles_spec',
  './lib/specs/mobile_device_performed_actions_spec',

  './lib/specs/mobile_device_administrator_spec',
  './lib/specs/mobile_device_certificate_spec',
  './lib/specs/mobile_device_custom_field_spec',
  './lib/specs/mobile_device_user_spec',
  './lib/specs/mobile_policy_spec',
  './lib/specs/mobile_policy_from_content_spec',
  './lib/specs/mobile_policy_from_mobile_device_spec',
  './lib/specs/mobile_policy_from_action_spec',
  './lib/specs/in_house_application_spec',
  './lib/specs/in_house_application_from_policy_spec',
  './lib/specs/third_party_application_spec',
  './lib/specs/third_party_application_from_policy_spec',
  './lib/specs/configuration_profile_spec',
  './lib/specs/configuration_profile_from_policy_spec',
  './lib/specs/provisioning_profile_spec',
  './lib/specs/actions_spec',
  './lib/specs/actions_from_policy_spec',

  './lib/specs/vpp_accounts_spec',

  './lib/specs/custom_field_spec',

  './lib/specs/command_computer_queue_spec',
  './lib/specs/command_computer_history_spec',
  './lib/specs/command_mobile_queue_spec',
  './lib/specs/command_mobile_history_spec',
  './lib/specs/command_group_spec',
  './lib/specs/user_prefs_spec',
  './lib/specs/assignable_item_menu_spec',
  './lib/specs/book_spec',

  './lib/specs/computer_list_spec',
  './lib/specs/computer_group_spec',
  './lib/specs/computer_item_memory_spec',
  './lib/specs/computer_item_agent_information_spec',
  './lib/specs/computer_item_hardware_spec',
  './lib/specs/computer_item_system_software_spec',
  './lib/specs/computer_item_cpu_spec',
  './lib/specs/computer_item_missing_patch_pc_spec',
  './lib/specs/computer_item_missing_patch_mac_spec',
  './lib/specs/computer_item_volume_pc_spec',
  './lib/specs/computer_item_volume_mac_spec',
  './lib/specs/computer_item_network_adapter_spec',
  './lib/specs/computer_item_installed_software_pc_spec',
  './lib/specs/computer_item_installed_software_mac_spec',
  './lib/specs/computer_item_installed_profile_spec',

  './lib/specs/user_self_help_device_list_spec',
  './lib/specs/user_self_help_location_accuracy_spec',
  './lib/specs/user_self_help_tracking_interval_period_spec',
  './lib/specs/user_self_help_privileges_spec',

  'i18n!./nls/strings'
], function(
  Em,
  AbsData,
  AmData,

  FilterSerialization,

  AdHocStore,
  MobileDeviceStore,
  MobileDeviceItemStore,
  MobileDeviceGroupStore,
  MobileDeviceFromMobilePolicyStore,
  MobileDeviceFromContentStore,
  MobileDeviceInstalledApplicationStore,
  MobileDeviceInstalledConfigProfileStore,
  MobileDeviceInstalledProvisioningProfileStore,
  MobileDeviceAssignedAppsStore,
  MobileDeviceAssignedInHouseAppsStore,
  MobileDeviceAssignedProfilesStore,
  MobileDevicePerformedActionsStore,

  MobileDeviceAdministratorStore,
  MobileDeviceCertificateStore,
  MobileDeviceCustomFieldStore,
  MobileDeviceUserStore,
  MobilePolicyStore,
  MobilePolicyFromContentStore,
  MobilePolicyFromMobileDeviceStore,
  MobilePolicyFromActionStore,
  ContentStore,
  ContentFromMobilePolicyStore,
  ContentFromMobileDeviceStore,
  InHouseApplicationStore,
  ThirdPartyApplicationStore,
  InHouseApplicationFromPolicyStore,
  ThirdPartyApplicationFromPolicyStore,
  ConfigurationProfileStore,
  ConfigurationProfileFromPolicyStore,
  ProvisioningProfileStore,
  ActionsStore,
  ActionsFromPolicyStore,
  ActionWallpaperStore,

  VppAccountsStore,

  CustomFieldStore,
  CustomFieldDataTypeStore,
  CustomFieldFormatAsStore,
  CustomFieldEnumStore,

  CommandHistoryStore,
  CommandQueueStore,
  CommandComputerHistoryStore,
  CommandComputerQueueStore,
  CommandComputerDetailStore,
  CommandGroupStore,

  UserPrefsStore,
  AssignableItemMenuStore,
  BookStore,
  SmartPolicyStore,

  ComputerStore,
  ComputerGroupStore,
  ComputerItemMemoryStore,
  ComputerItemAgentInfoStore,
  ComputerItemHardwareStore,
  ComputerItemSystemSoftwareStore,
  ComputerItemCpuStore,
  ComputerItemVolumePcStore,
  ComputerItemVolumeMacStore,
  ComputerItemNetworkAdapterStore,
  ComputerItemMissingPatchPcStore,
  ComputerItemMissingPatchMacStore,
  ComputerItemInstalledSoftwarePcStore,
  ComputerItemInstalledSoftwareMacStore,
  ComputerItemInstalledProfileStore,

  UserSelfHelpDeviceListStore,
  UserSelfHelpLocationAccuracyStore,
  UserSelfHelpTrackingIntervalPeriodStore,
  UserSelfHelpPrivilegesStore,

  AmMobileDeviceClearPasscodeAction,
  AmMobileDeviceLockAction,
  AmMobileDeviceRemoteEraseAction,
  AmMobileDeviceSendMessageAction,
  AmMobileDeviceSetRoamingOptionsAction,
  AmMobileDeviceSetOwnershipAction,
  AmMobileDeviceSetEnrollmentUserAction,
  AmMobileDeviceSetDeviceNameAction,
  AmMobileDeviceSetOrganizationInfoAction,
  AmMobileDeviceRetryAllFailedProfilesAction,
  AmMobileDeviceRetryAllFailedAppsAction,
  AmMobileDeviceRetryAllTockenAction,
  AmMobileDeviceSetActivationLockOptionsAction,
  AmMobileDeviceChangeApplicationConfigurationAction,

  AmMobileDeviceUpdateInfoAction,
  AmMobileDeviceInstallApplicationAction,
  AmMobileDeviceUninstallApplicationAction,
  AmMobileDeviceInstallConfigProfileAction,
  AmMobileDeviceInstallProvisioningProfileAction,
  AmMobileDeviceUninstallConfigProfileAction,
  AmMobileDeviceUninstallProvisioningProfileAction,
  AmMobileDeviceRelatedCustomFieldDataDeleteAction,
  AmMobileDeviceRelatedCustomFieldDataUpdateAction,
  AmMobileDeviceRelatedPerformedActionRemoveAction,
  AmMobileDeviceRelatedPerformedActionReapplyAction,

  AmCustomFieldDeleteAction,
  AmCustomFieldUpdateAction,

  AmMobilePolicyToContentMapActionData,
  AmMobilePolicyToContentMapCreateAction,
  AmMobilePolicyToContentMapDeleteAction,

  AmMobilePolicyToMobileDeviceMapCreateAction,
  AmMobilePolicyToMobileDeviceMapDeleteAction,
  AmMobilePolicySetPolicyNameAction,
  AmMobilePolicyCreateSmartPolicyAction,
  AmMobilePolicyUpdateSmartPolicyAction,
  AmMobilePolicyDeletePolicyAction,
  AmMobilePolicyRenamePolicyAction,
  AmMobilePolicyAddConfigProfileAction,
  AmMobilePolicyRemoveConfigProfileAction,
  AmMobilePolicyAddInHouseAppAction,
  AmMobilePolicyRemoveInHouseAppAction,
  AmMobilePolicyAddThirdPartyAppAction,
  AmMobilePolicyRemoveThirdPartyAppAction,
  AmMobilePolicyReexecuteAction,

  AmContentActionData,
  AmContentCreateBatchAction,
  AmContentUpdateAction,
  AmContentDeleteAction,
  UpdateUserPrefAction,

  AmCommandHistoryDeleteAction,
  AmCommandQueueDeleteAction,
  AmComputerCommandHistoryDeleteAction,
  AmComputerCommandQueueDeleteAction,

  AmComputerSendMessageAction,
  AmComputerGatherInventoryCommandsAction,

  AmUserSelfHelpDeviceLockAction,
  AmUserSelfHelpDeviceRemoteEraseAction,
  AmUserSelfHelpDeviceResetTrackingPasscodeAction,
  AmUserSelfHelpDeviceTrackAction,
  AmUserSelfHelpDeviceSendMessageAction,
  AmUserSelfHelpDeviceClearOrSetTrackingPasscodeAction,

  AmActionAddUpdateAction,
  AmActionDeleteAction,
  AmActionAddUpdatePolicyAssignmentAction,
  AmActionDeletePolicyAssignmentAction,

  AmContent,

  AmContentSpec,
  AmContentFromMobilePolicySpec,
  AmContentFromMobileDeviceSpec,
  AmMobileDeviceSpec,
  AmMobileDeviceGroupSpec,
  AmMobileDeviceFromMobilePolicySpec,
  AmMobileDeviceFromMobileContentSpec,
  AmMobileDeviceInstalledApplicationSpec,
  AmMobileDeviceInstalledConfigProfileSpec,
  AmMobileDeviceInstalledProvisioningProfileSpec,
  AmMobileDeviceAssignedAppsSpec,
  AmMobileDeviceAssignedInHouseAppsSpec,
  AmMobileDeviceAssignedProfilesSpec,
  AmMobileDevicePerformedActionsSpec,

  AmMobileDeviceAdministratorSpec,
  AmMobileDeviceCertificateSpec,
  AmMobileDeviceCustomFieldSpec,
  AmMobileDeviceUserSpec,
  AmMobilePolicySpec,
  AmMobilePolicyFromContentSpec,
  AmMobilePolicyFromMobileDeviceSpec,
  AmMobilePolicyFromActionSpec,
  AmInHouseApplicationSpec,
  AmInHouseApplicationFromPolicySpec,
  AmThirdPartyApplicationSpec,
  AmThirdPartyApplicationFromPolicySpec,
  AmConfigurationProfileSpec,
  AmConfigurationProfileFromPolicySpec,
  AmProvisioningProfileSpec,
  AmActionsSpec,
  AmActionsFromPolicySpec,

  AmVppAccountsSpec,

  AmCustomFieldSpec,

  AmCommandQueueSpec,
  AmCommandHistorySpec,
  AmCommandComputerQueueSpec,
  AmCommandComputerHistorySpec,
  AmCommandGroupSpec,
  UserPrefsSpec,
  AmAssignableItemMenuSpec,
  AmBookSpec,

  AmComputerSpec,
  AmComputerGroupSpec,
  AmComputerMemorySpec,
  AmComputerAgentInfoSpec,
  AmComputerHardwareSpec,
  AmComputerSystemSoftwareSpec,
  AmComputerCpuSpec,
  AmComputerMissingPatchPcSpec,
  AmComputerMissingPatchMacSpec,
  AmComputerVolumePcSpec,
  AmComputerVolumeMacSpec,
  AmComputerNetworkAdapterSpec,
  AmComputerInstalledSoftwarePcSpec,
  AmComputerInstalledSoftwareMacSpec,
  AmComputerInstalledProfileSpec,

  UserSelfHelpDeviceListSpec,
  AmUserSelfHelpLocationAccuracySpec,
  AmUserSelfHelpTrackingIntervalPeriodSpec,
  AmUserSelfHelpPrivilegesSpec,

  strings
) {
  'use strict';

  return AmData.reopen({
    appStrings: strings,

    urlRoot: '/com.absolute.am.webapi',

    filterSerialization: FilterSerialization.create(),

    specs: Em.Object.create({
      AmContentSpec: AmContentSpec,
      AmContentFromMobilePolicySpec: AmContentFromMobilePolicySpec,
      AmContentFromMobileDeviceSpec: AmContentFromMobileDeviceSpec,
      AmMobileDeviceSpec: AmMobileDeviceSpec,
      AmMobileDeviceGroupSpec: AmMobileDeviceGroupSpec,
      AmMobileDeviceFromMobilePolicySpec: AmMobileDeviceFromMobilePolicySpec,
      AmMobileDeviceFromMobileContentSpec: AmMobileDeviceFromMobileContentSpec,
      AmMobileDeviceInstalledApplicationSpec: AmMobileDeviceInstalledApplicationSpec,
      AmMobileDeviceInstalledConfigProfileSpec: AmMobileDeviceInstalledConfigProfileSpec,
      AmMobileDeviceInstalledProvisioningProfileSpec: AmMobileDeviceInstalledProvisioningProfileSpec,
      AmMobileDeviceAssignedAppsSpec: AmMobileDeviceAssignedAppsSpec,
      AmMobileDeviceAssignedInHouseAppsSpec: AmMobileDeviceAssignedInHouseAppsSpec,
      AmMobileDeviceAssignedProfilesSpec: AmMobileDeviceAssignedProfilesSpec,
      AmMobileDevicePerformedActionsSpec: AmMobileDevicePerformedActionsSpec,

      AmMobileDeviceAdministratorSpec: AmMobileDeviceAdministratorSpec,
      AmMobileDeviceCertificateSpec: AmMobileDeviceCertificateSpec,
      AmMobileDeviceCustomFieldSpec: AmMobileDeviceCustomFieldSpec,
      AmMobileDeviceUserSpec: AmMobileDeviceUserSpec,
      AmMobilePolicySpec: AmMobilePolicySpec,
      AmMobilePolicyFromContentSpec: AmMobilePolicyFromContentSpec,
      AmMobilePolicyFromMobileDeviceSpec: AmMobilePolicyFromMobileDeviceSpec,
      AmMobilePolicyFromActionSpec: AmMobilePolicyFromActionSpec,
      AmInHouseApplicationSpec: AmInHouseApplicationSpec,
      AmInHouseApplicationFromPolicySpec: AmInHouseApplicationFromPolicySpec,
      AmThirdPartyApplicationSpec: AmThirdPartyApplicationSpec,
      AmThirdPartyApplicationFromPolicySpec: AmThirdPartyApplicationFromPolicySpec,
      AmConfigurationProfileSpec: AmConfigurationProfileSpec,
      AmConfigurationProfileFromPolicySpec: AmConfigurationProfileFromPolicySpec,
      AmProvisioningProfileSpec: AmProvisioningProfileSpec,
      AmActionsSpec: AmActionsSpec,
      AmActionsFromPolicySpec: AmActionsFromPolicySpec,

      AmVppAccountsSpec: AmVppAccountsSpec,

      AmCustomFieldSpec: AmCustomFieldSpec,

      AmCommandQueueSpec: AmCommandQueueSpec,
      AmCommandHistorySpec: AmCommandHistorySpec,
      AmCommandComputerQueueSpec: AmCommandComputerQueueSpec,
      AmCommandComputerHistorySpec: AmCommandComputerHistorySpec,
      AmCommandGroupSpec: AmCommandGroupSpec,
      UserPrefsSpec: UserPrefsSpec,
      AmAssignableItemMenuSpec: AmAssignableItemMenuSpec,
      AmBookSpec: AmBookSpec,

      AmComputerSpec: AmComputerSpec,
      AmComputerGroupSpec: AmComputerGroupSpec,
      AmComputerMemorySpec: AmComputerMemorySpec,
      AmComputerAgentInfoSpec: AmComputerAgentInfoSpec,
      AmComputerHardwareSpec: AmComputerHardwareSpec,
      AmComputerSystemSoftwareSpec: AmComputerSystemSoftwareSpec,
      AmComputerCpuSpec: AmComputerCpuSpec,
      AmComputerMissingPatchPcSpec: AmComputerMissingPatchPcSpec,
      AmComputerMissingPatchMacSpec: AmComputerMissingPatchMacSpec,
      AmComputerVolumePcSpec: AmComputerVolumePcSpec,
      AmComputerVolumeMacSpec: AmComputerVolumeMacSpec,
      AmComputerNetworkAdapterSpec: AmComputerNetworkAdapterSpec,
      AmComputerInstalledSoftwarePcSpec: AmComputerInstalledSoftwarePcSpec,
      AmComputerInstalledSoftwareMacSpec: AmComputerInstalledSoftwareMacSpec,
      AmComputerInstalledProfileSpec: AmComputerInstalledProfileSpec,

      UserSelfHelpDeviceListSpec: UserSelfHelpDeviceListSpec,
      AmUserSelfHelpLocationAccuracy: AmUserSelfHelpLocationAccuracySpec,
      AmUserSelfHelpTrackingIntervalPeriod: AmUserSelfHelpTrackingIntervalPeriodSpec,
      AmUserSelfHelpPrivilegesSpec: AmUserSelfHelpPrivilegesSpec
    }),

    models: Em.Object.create({
      AmContent: AmContent
    }),

    stores: null,

    actions: Em.Object.create({
      AmMobileDeviceClearPasscodeAction: AmMobileDeviceClearPasscodeAction,
      AmMobileDeviceLockAction: AmMobileDeviceLockAction,
      AmMobileDeviceRemoteEraseAction: AmMobileDeviceRemoteEraseAction,
      AmMobileDeviceSendMessageAction: AmMobileDeviceSendMessageAction,
      AmMobileDeviceSetRoamingOptionsAction: AmMobileDeviceSetRoamingOptionsAction,
      AmMobileDeviceSetOwnershipAction: AmMobileDeviceSetOwnershipAction,
      AmMobileDeviceSetEnrollmentUserAction: AmMobileDeviceSetEnrollmentUserAction,
      AmMobileDeviceSetDeviceNameAction: AmMobileDeviceSetDeviceNameAction,
      AmMobileDeviceSetOrganizationInfoAction: AmMobileDeviceSetOrganizationInfoAction,
      AmMobileDeviceRetryAllFailedProfilesAction: AmMobileDeviceRetryAllFailedProfilesAction,
      AmMobileDeviceRetryAllFailedAppsAction: AmMobileDeviceRetryAllFailedAppsAction,
      AmMobileDeviceRetryAllTockenAction: AmMobileDeviceRetryAllTockenAction,
      AmMobileDeviceSetActivationLockOptionsAction:AmMobileDeviceSetActivationLockOptionsAction,
      AmMobileDeviceChangeApplicationConfigurationAction: AmMobileDeviceChangeApplicationConfigurationAction,

      AmMobileDeviceUpdateInfoAction: AmMobileDeviceUpdateInfoAction,
      AmMobileDeviceInstallApplicationAction: AmMobileDeviceInstallApplicationAction,
      AmMobileDeviceUninstallApplicationAction: AmMobileDeviceUninstallApplicationAction,
      AmMobileDeviceInstallConfigProfileAction: AmMobileDeviceInstallConfigProfileAction,
      AmMobileDeviceUninstallConfigProfileAction: AmMobileDeviceUninstallConfigProfileAction,
      AmMobileDeviceInstallProvisioningProfileAction: AmMobileDeviceInstallProvisioningProfileAction,
      AmMobileDeviceUninstallProvisioningProfileAction: AmMobileDeviceUninstallProvisioningProfileAction,
      AmMobileDeviceRelatedCustomFieldDataDeleteAction: AmMobileDeviceRelatedCustomFieldDataDeleteAction,
      AmMobileDeviceRelatedCustomFieldDataUpdateAction: AmMobileDeviceRelatedCustomFieldDataUpdateAction,
      AmMobileDeviceRelatedPerformedActionRemoveAction: AmMobileDeviceRelatedPerformedActionRemoveAction,
      AmMobileDeviceRelatedPerformedActionReapplyAction: AmMobileDeviceRelatedPerformedActionReapplyAction,

      AmCustomFieldDeleteAction:AmCustomFieldDeleteAction,
      AmCustomFieldUpdateAction:AmCustomFieldUpdateAction,

      AmComputerSendMessageAction: AmComputerSendMessageAction,
      AmComputerGatherInventoryCommandsAction: AmComputerGatherInventoryCommandsAction,

      AmMobilePolicyToContentMapActionData: AmMobilePolicyToContentMapActionData,
      AmMobilePolicyToContentMapCreateAction: AmMobilePolicyToContentMapCreateAction,
      AmMobilePolicyToContentMapDeleteAction: AmMobilePolicyToContentMapDeleteAction,

      AmMobilePolicyToMobileDeviceMapCreateAction: AmMobilePolicyToMobileDeviceMapCreateAction,
      AmMobilePolicyToMobileDeviceMapDeleteAction: AmMobilePolicyToMobileDeviceMapDeleteAction,
      AmMobilePolicySetPolicyNameAction: AmMobilePolicySetPolicyNameAction,
      AmMobilePolicyCreateSmartPolicyAction: AmMobilePolicyCreateSmartPolicyAction,
      AmMobilePolicyUpdateSmartPolicyAction: AmMobilePolicyUpdateSmartPolicyAction,
      AmMobilePolicyDeletePolicyAction: AmMobilePolicyDeletePolicyAction,
      AmMobilePolicyRenamePolicyAction:AmMobilePolicyRenamePolicyAction,
      AmMobilePolicyAddConfigProfileAction: AmMobilePolicyAddConfigProfileAction,
      AmMobilePolicyRemoveConfigProfileAction: AmMobilePolicyRemoveConfigProfileAction,
      AmMobilePolicyAddInHouseAppAction: AmMobilePolicyAddInHouseAppAction,
      AmMobilePolicyRemoveInHouseAppAction: AmMobilePolicyRemoveInHouseAppAction,
      AmMobilePolicyAddThirdPartyAppAction: AmMobilePolicyAddThirdPartyAppAction,
      AmMobilePolicyRemoveThirdPartyAppAction: AmMobilePolicyRemoveThirdPartyAppAction,
      AmMobilePolicyReexecuteAction: AmMobilePolicyReexecuteAction,

      AmContentActionData: AmContentActionData,
      AmContentCreateBatchAction: AmContentCreateBatchAction,
      AmContentUpdateAction: AmContentUpdateAction,
      AmContentDeleteAction: AmContentDeleteAction,
      UpdateUserPrefAction: UpdateUserPrefAction,

      AmCommandHistoryDeleteAction: AmCommandHistoryDeleteAction,
      AmCommandQueueDeleteAction: AmCommandQueueDeleteAction,
      AmComputerCommandHistoryDeleteAction: AmComputerCommandHistoryDeleteAction,
      AmComputerCommandQueueDeleteAction: AmComputerCommandQueueDeleteAction,

      AmUserSelfHelpDeviceLockAction: AmUserSelfHelpDeviceLockAction,
      AmUserSelfHelpDeviceRemoteEraseAction: AmUserSelfHelpDeviceRemoteEraseAction,
      AmUserSelfHelpDeviceResetPasscodeAction: AmUserSelfHelpDeviceResetTrackingPasscodeAction,
      AmUserSelfHelpDeviceTrackAction: AmUserSelfHelpDeviceTrackAction,
      AmUserSelfHelpDeviceSendMessageAction: AmUserSelfHelpDeviceSendMessageAction,
      AmUserSelfHelpDeviceClearOrSetTrackingPasscodeAction: AmUserSelfHelpDeviceClearOrSetTrackingPasscodeAction,

      AmActionAddUpdateAction: AmActionAddUpdateAction,
      AmActionDeleteAction: AmActionDeleteAction,
      AmActionAddUpdatePolicyAssignmentAction: AmActionAddUpdatePolicyAssignmentAction,
      AmActionDeletePolicyAssignmentAction: AmActionDeletePolicyAssignmentAction
    }),

    initialize: function(App) {
      this.setProperties({
        stores: Em.Object.create({
          all: AbsData.get('allDataStores'),
          adHocStore: AdHocStore.create({ name: 'adHocStore' }),

          mobileDeviceStore: MobileDeviceStore.create({ name: 'mobileDevices' }),
          mobileDeviceItemStore: MobileDeviceItemStore.create({ name: 'mobileDevicesItem' }),
          mobileDeviceGroupStore: MobileDeviceGroupStore.create({ name: 'mobileDeviceGroups' }),
          mobileDeviceFromMobilePolicyStore: MobileDeviceFromMobilePolicyStore.create({ name: 'mobileDevicesFromMobilePolicies' }),
          mobileDeviceFromContentStore: MobileDeviceFromContentStore.create({ name: 'mobileDevicesFromContent' }),
          mobileDeviceInstalledAppStore: MobileDeviceInstalledApplicationStore.create({ name: 'mobileDeviceInstalledApps' }),
          mobileDeviceInstalledConfigProfileStore: MobileDeviceInstalledConfigProfileStore.create({ name: 'mobileDeviceInstalledConfigProfiles' }),
          mobileDeviceInstalledProvisioningProfileStore: MobileDeviceInstalledProvisioningProfileStore.create({ name: 'mobileDeviceInstalledProvisioningProfiles' }),
          mobileDeviceAssignedAppsStore: MobileDeviceAssignedAppsStore.create({ name: 'mobileDeviceAssignedApps' }),
          mobileDeviceAssignedInHouseAppsStore: MobileDeviceAssignedInHouseAppsStore.create({ name: 'mobileDeviceAssignedInHouseApps' }),
          mobileDeviceAssignedProfilesStore: MobileDeviceAssignedProfilesStore.create({ name: 'mobileDeviceAssignedProfiles' }),
          mobileDevicePerformedActionsStore: MobileDevicePerformedActionsStore.create({ name: 'mobileDevicePerformedActions' }),

          mobileDeviceAdministratorStore: MobileDeviceAdministratorStore.create({ name: 'mobileDeviceAdministrators' }),
          mobileDeviceCertificateStore: MobileDeviceCertificateStore.create({ name: 'mobileDeviceCertificates' }),
          mobileDeviceCustomFieldStore: MobileDeviceCustomFieldStore.create({ name: 'mobileDeviceCustomFields' }),
          mobileDeviceUserStore: MobileDeviceUserStore.create({ name: 'mobileDeviceUser' }),
          mobilePolicyStore: MobilePolicyStore.create({ name: 'mobilePolicies' }),
          mobilePolicyFromContentStore: MobilePolicyFromContentStore.create({ name: 'mobilePoliciesFromContent' }),
          mobilePolicyFromMobileDeviceStore: MobilePolicyFromMobileDeviceStore.create({ name: 'mobilePoliciesFromMobileDevices' }),
          mobilePolicyFromActionStore: MobilePolicyFromActionStore.create({ name: 'mobilePoliciesFromAction' }),
          contentStore: ContentStore.create({ name: 'content' }),
          contentFromMobilePolicyStore: ContentFromMobilePolicyStore.create({ name: 'contentFromMobilePolicies' }),
          contentFromMobileDeviceStore: ContentFromMobileDeviceStore.create({ name: 'contentFromMobileDevices' }),
          inHouseApplicationStore: InHouseApplicationStore.create({ name: 'inHouseApplications' }),
          thirdPartyApplicationStore: ThirdPartyApplicationStore.create({ name: 'thirdPartyApplications' }),
          inHouseApplicationFromPolicyStore: InHouseApplicationFromPolicyStore.create({ name: 'inHouseApplications' }),
          thirdPartyApplicationFromPolicyStore: ThirdPartyApplicationFromPolicyStore.create({ name: 'thirdPartyApplications' }),
          configurationProfileStore: ConfigurationProfileStore.create({ name: 'mobileDeviceConfigProfiles' }),
          configurationProfileFromPolicyStore: ConfigurationProfileFromPolicyStore.create({ name: 'mobilePolicyConfigProfiles' }),
          provisioningProfileStore: ProvisioningProfileStore.create({ name: 'mobileDeviceProvisioningProfiles' }),
          actionsStore: ActionsStore.create({ name: 'assignableActions' }),
          actionsFromPolicyStore: ActionsFromPolicyStore.create({ name: 'actionsFromPolicy' }),
          actionWallpaperStore: ActionWallpaperStore.create({ name: 'actionWallpaper' }),

          vppAccountsStore: VppAccountsStore.create({ name: 'vppAccounts' }),

          customFieldStore: CustomFieldStore.create({ name: 'customFieldStore' }),
          customFieldDataTypeStore: CustomFieldDataTypeStore.create({ name: 'customFieldDataTypeStore' }),
          customFieldFormatAsStore: CustomFieldFormatAsStore.create({ name: 'customFieldFormatAsStore' }),
          customFieldEnumStore: CustomFieldEnumStore.create({ name: 'customFieldEnumStore' }),

          commandHistoryStore: CommandHistoryStore.create({ name: 'commandHistory' }),
          commandQueueStore: CommandQueueStore.create({ name: 'commandQueue' }),

          computerStore: ComputerStore.create({ name: 'computerStore' }),
          computerGroupStore: ComputerGroupStore.create({ name: 'computerGroupStore' }),
          computerItemAgentInfoStore: ComputerItemAgentInfoStore.create({ name: 'computerItemAgentInfoStore' }),
          computerItemMemoryStore: ComputerItemMemoryStore.create({ name: 'computerItemMemoryStore' }),
          computerItemHardwareStore: ComputerItemHardwareStore.create({ name: 'computerItemHardwareStore' }),
          computerItemSystemSoftwareStore: ComputerItemSystemSoftwareStore.create({ name: 'computerItemSystemSoftwareStore' }),
          computerItemCpuStore: ComputerItemCpuStore.create({ name: 'computerItemCpuStore' }),
          computerItemVolumePcStore: ComputerItemVolumePcStore.create({ name: 'computerItemVolumePcStore' }),
          computerItemVolumeMacStore: ComputerItemVolumeMacStore.create({ name: 'computerItemVolumeMacStore' }),
          computerItemNetworkAdapterStore: ComputerItemNetworkAdapterStore.create({ name: 'computerItemNetworkAdapterStore' }),
          computerItemMissingPatchPcStore: ComputerItemMissingPatchPcStore.create({ name: 'computerItemMissingPatchPcStore' }),
          computerItemMissingPatchMacStore: ComputerItemMissingPatchMacStore.create({ name: 'computerItemMissingPatchMacStore' }),
          computerItemInstalledSoftwarePcStore: ComputerItemInstalledSoftwarePcStore.create({ name: 'computerItemInstalledSoftwarePcStore' }),
          computerItemInstalledSoftwareMacStore: ComputerItemInstalledSoftwareMacStore.create({ name: 'computerItemInstalledSoftwareMacStore' }),
          computerItemInstalledProfileStore: ComputerItemInstalledProfileStore.create({ name: 'computerItemInstalledProfileStore' }),

          commandMobileHistoryStore: CommandHistoryStore.create({ name: 'commandHistory' }),
          commandMobileQueueStore: CommandQueueStore.create({ name: 'commandQueue' }),
          commandComputerHistoryStore: CommandComputerHistoryStore.create({ name: 'commandComputerHistoryStore' }),
          commandComputerQueueStore: CommandComputerQueueStore.create({ name: 'commandComputerQueueStore' }),
          commandComputerDetailStore: CommandComputerDetailStore.create({ name: 'commandComputerDetailStore' }),
          commandGroupStore: CommandGroupStore.create({ name: 'commandGroupStore' }),

          userPrefsStore: UserPrefsStore.create({ name: 'userPrefsStore' }),
          assignableItemMenuStore: AssignableItemMenuStore.create({ name: 'assignableItemMenuStore' }),
          bookStore: BookStore.create({ name: 'bookStore' }),
          smartPolicyStore: SmartPolicyStore.create({ name: 'bookStore' }),

          userSelfHelpDeviceListStore: UserSelfHelpDeviceListStore.create({ name: 'userSelfHelpDeviceListStore' }),
          userSelfHelpLocationAccuracyStore: UserSelfHelpLocationAccuracyStore.create({ name: 'userSelfHelpLocationAccuracyStore' }),
          userSelfHelpTrackingIntervalPeriodStore: UserSelfHelpTrackingIntervalPeriodStore.create({ name: 'userSelfHelpTrackingIntervalPeriodStore' }),
          userSelfHelpPrivilegesStore: UserSelfHelpPrivilegesStore.create({ name: 'userSelfHelpPrivilegesStore' })
        })
      });
    }
  });
});
