define({
  "root": {
    "amData": {
        "policyFromActionSpec": {
            "policyName": "Policy Name",
            "repeatCount": "Repeat Count",
            "repeatInterval": "Repeat Interval",
            "initialDelay": "Initial Delay"
        },
        "mobileDeviceSpec": {
            "name": "Device Name",
            "model": "Model",
            "osVersion": "OS Version",
            "serialNumber": "Serial Number",
            "lastContact": "Last Contact",
            "osPlatform": "OS Type",
            "isManaged": "Managed",
            "absoluteAppsVersion": "AbsoluteApps Version",
            "dataRoamingEnabled": "Data Roaming Enabled",
            "voiceRoamingEnabled": "Voice Roaming Enabled",
            "isPasscodePresent": "Passcode Present",
            "cellularTechnology": "Cellular Technology",
            "osBuildNumber": "OS Build Number",
            "isGpsCapable": "GPS Capable",
            "isJailBroken": "Jailbroken",
            "isMdmProfileUpToDate": "MDM Profile Up-To-Date",
            "isTablet": "Tablet",
            "isPasscodeCompliant": "Passcode Compliant",
            "isPasscodeCompliantWithProfiles": "Passcode Compliant with Profiles"
        },
        "commandGroupStore": {
            "computerLabel": "Computers",
            "mobileDeviceLabel": "Mobile Devices"
        },
        "commandMobileQueueSpec": {
            "command": "Command",
            "deviceName": "Device Name",
            "deviceModel": "Device Model",
            "osVersion": "OS Version",
            "status": "Status",
            "timeIssued": "Time Issued"
        },
        "commandMobileHistorySpec": {
            "command": "Command",
            "deviceName": "Device Name",
            "deviceModel": "Device Model",
            "osVersion": "OS Version",
            "timeIssued": "Time Issued",
            "timeFinished": "Finish Time",
            "commandError": "Command Error",
            "commandErrorInfo": "Command Error Info"
        },
        "commandComputerQueueSpec": {
            "status": "Command Status",
            "statusNumber": "Status Number",
            "commandName": "Command",
            "commandUUID": "Command UUID",
            "administratorName": "Administrator Name",
            "computerEsn": "ESN",
            "agentName": "Device Name",
            "scheduledTime": "Scheduled Time"
        },
        "commandComputerHistorySpec": {
            "status": "Command Status",
            "statusNumber": "Status Number",
            "commandName": "Command",
            "commandUUID": "Command UUID",
            "administratorName": "Administrator Name",
            "computerEsn": "ESN",
            "agentName": "Device Name",
            "startTime": "Start Time",
            "commandError": "Command Error",
            "commandErrorInfo": "Command Error Info"
        },
        "mobilePolicySpec": {
            "name": "Policy Name",
            "isSmartPolicy": "Smart Policy",
            "guid": "GUID",
            "unmanagedDevices": "Unmanaged devices"
        },
        "thirdPartyApplicationsFromPolicySpec": {
            "icon": "Icon",
            "name": "App Name",
            "osPlatform": "OS",
            "category": "Category",
            "minOsVersion": "Compatibility",
            "shortDescription": "Short Description",
            "longDescription": "Long Description",
            "appStoreURL": "App Store Web Page",
            "isUniversal": "Universal",
            "supportedDevices": "Supported Devices",
            "preventDataBackup": "Prevent Data Backup",
            "removeWhenMDMIsRemoved": "Remove When MDM Is Removed",
            "hasRedemptionCode": "Has Redemption Code",
            "vppCodesPurchased": "VPP Purchased",
            "vppCodesRedeemed": "VPP Redeemed",
            "vppCodesRemaining": "VPP Remaining",
            "assignmentRule": "Rule"
        },
        "mobileDeviceAssignedApsSpec": {
            "icon": "Icon",
            "appName": "App Name",
            "policyName": "Policy Name",
            "rule": "Rule"
        },
        "mobileDeviceInstalledApplicationSpec": {
            "name": "App Name",
            "versionString": "Version String",
            "buildNumber": "Build Number",
            "bundleIdentifier": "Bundle Identifier",
            "packageName": "Package Name",
            "appSize": "App Size",
            "appStatus": "App Status",
            "dataSize": "App Data Size",
            "preventDataBackup": "Prevent Data Backup",
            "boundToMDM": "Bound To MDM",
            "appInstallDirectory": "Installed App Data Directory"
        },
        "inHouseApplicationFromPolicySpec": {
            "name": "App Name",
            "osPlatform": "OS Type",
            "version": "Version",
            "buildNumber": "Build Number",
            "size": "Size",
            "shortDescription": "Short Description",
            "longDescription": "Long Description",
            "bundleIdentifier": "Bundle Identifier",
            "packageName": "Package Name",
            "minOsVersion": "Compatibility",
            "isUniversal": "Universal",
            "supportedDevices": "Supported Devices",
            "provisioningProfile": "iOS Provisioning Profile Name",
            "provProfileExpiryDate": "iOS Provisioning Profile Expiry Date",
            "assignmentRule": "Rule"
        },
        "mobilePolicyAssignedApsSpec": {
            "appName": "App Name",
            "policyName": "Policy Name",
            "rule": "Rule"
        },
        "contentToMobilePolicyAssignmentSpec": {
            "policyName": "Policy Name",
            "isSmartPolicy": "Smart Policy",
            "mediaFileAssignmentType": "Assignment Rule",
            "mediaFileAssignmentAvailability": "Availability",
            "mediaFileAssignmentStartTime": "Start Time",
            "mediaFileAssignmentEndTime": "End Time"
        },
        "mobileDeviceInstalledConfigurationProfileSpec": {
            "name": "Profile Name",
            "description": "Description",
            "organization": "Issuing Organization",
            "profileType": "Profile Type",
            "identifier": "Profile Identifier",
            "uuid": "Profile UUID",
            "isEncrypted": "Profile Encrypted",
            "isManaged": "Profile Managed",
            "allowRemoval": "Allow Removal"
        },
        "configurationProfileFromPolicySpec": {
            "name": "Profile Name",
            "description": "Description",
            "organization": "Issuing Organization",
            "osPlatform": "OS Type",
            "profileType": "Profile Type",
            "identifier": "Profile Identifier",
            "uuid": "Profile UUID",
            "allowRemoval": "Allow Removal",
            "variablesUsed": "Variables Used",
            "availabilitySelector": "Availability",
            "profileStartTime": "Start Time",
            "profileEndTime": "End Time",
            "assignmentRule": "Assignment Rule"
        },
        "mobileDeviceAssignedProfilesSpec": {
            "profileName": "Profile Name",
            "policyName": "Policy Name",
            "availabilitySelector": "Availability",
            "profileStartTime": "Start Time",
            "profileEndTime": "End Time"
        },
        "administratorSpec": {
            "administratorName": "Administrator Name"
        },
        "certificateSpec": {
            "name": "Certificate Name",
            "isIdentity": "Identity Certificate"
        },
        "installedProvisioningProfileSpec": {
            "uuid": "UUID",
            "name": "Profile Name",
            "expiry": "Profile Expiry Date"
        },
        "performedActionsSpec": {
            "name": "Name",
            "description": "Description",
            "policyName": "Policy Name",
            "type": "Type",
            "executionTime": "Execution Time"
        },
        "contentSpec": {
            "name": "Name",
            "description": "Description",
            "mediaFileName": "File Name",
            "type": "Type",
            "mediaCategory": "Media Category",
            "modified": "Last Modified",
            "mediaFileSize": "File Size",
            "wifiOnly": "Wi-Fi Only",
            "canLeaveAbsSafe": "Can Leave AbsoluteSafe",
            "canBeEmailed": "Can Be Emailed",
            "canBePrinted": "Can Be Printed",
            "hashedPassword": "Hashed Password"
        },
        "inHouseApplicationSpec": {
            "name": "App Name",
            "osPlatform": "OS Type",
            "version": "Version",
            "buildNumber": "Build Number",
            "size": "Size",
            "shortDescription": "Short Description",
            "longDescription": "Long Description",
            "bundleIdentifier": "Bundle Identifier",
            "packageName": "Package Name",
            "minOsVersion": "Compatibility",
            "isUniversal": "Universal",
            "supportedDevices": "Supported Devices",
            "provisioningProfile": "iOS Provisioning Profile Name",
            "provProfileExpiryDate": "iOS Provisioning Profile Expiry Date"
        },
        "thirdPartyApplicationsSpec": {
            "icon": "Icon",
            "name": "App Name",
            "osPlatform": "OS",
            "category": "Category",
            "minOsVersion": "Compatibility",
            "shortDescription": "Short Description",
            "longDescription": "Long Description",
            "appStoreURL": "App Store Web Page",
            "isUniversal": "Universal",
            "supportedDevices": "Supported Devices",
            "preventDataBackup": "Prevent Data Backup",
            "removeWhenMDMIsRemoved": "Remove When MDM Is Removed",
            "hasRedemptionCode": "Has Redemption Code",
            "vppCodesPurchased": "VPP Purchased",
            "vppCodesRedeemed": "VPP Redeemed",
            "vppCodesRemaining": "VPP Remaining",
            "assignmentRule": "Rule"
        },
        "assignableBookstoreBookSpec": {
            "name": "Title",
            "category": "Category",
            "shortDescription": "Short Description",
            "icon": "Icon"
        },
        "configurationProfileSpec": {
            "name": "Profile Name",
            "description": "Description",
            "organization": "Issuing Organization",
            "osPlatform": "OS Type",
            "profileType": "Profile Type",
            "identifier": "Profile Identifier",
            "uuid": "Profile UUID",
            "allowRemoval": "Allow Removal",
            "variablesUsed": "Variables Used"
        },
        "provisioningProfileSpec": {
            "name": "Profile Name",
            "expiry": "Profile Expiry Date",
            "uuid": "UUID"
        },
        "actionsSpec": {
            "name": "Action Name",
            "type": "Action Type",
            "description": "Action Description",
            "osPlatform": "Action Supported Platforms",
            "lastModified": "Last Modified"
        },
        "mobileDeviceFromMobilePolicySpec": {
            "name": "Name",
            "model": "Model",
            "osVersion": "OS Version",
            "serialNumber": "Serial Number",
            "phoneNumber": "Phone Number",
            "lastContact": {
                "value": "Last Contact",
                "comment": "JA - last accessed date and time"
            },
            "simIccId": "SIM ICC Identifier",
            "imei": "IMEI",
            "osPlatform": "OS Type",
            "osBuildNumber": "OS Build Number"
        },
        "mobileDeviceGroupStore": {
            "allMobileDevices": "All Mobile Devices",
            "allAndroidDevices": "All Android Devices",
            "allAndroidTablets": "All Android Tablets",
            "allAndroidPhones": "All Android Phones",
            "alliOSDevices": "All iOS Devices",
            "alliPhones": "All iPhones",
            "alliPads": "All iPads",
            "alliPodTouchDevices": "All iPod Touch Devices",
            "allWindowsPhoneDevices": "All Windows Phone Devices"
        },
        "assignableItemMenuStore": {
            "content": "Content",
            "inHouseApplications": "In-House Applications",
            "thirdPartyApplications": "Third-Party Applications",
            "bookstoreBooks": "Bookstore Books",
            "configurationProfiles": "Configuration Profiles",
            "provisioningProfiles": "Provisioning Profiles",
            "actions": "Actions"
        },
        "computerGroupStore": {
            "allComputers": "All Computers",
            "allPCs": "PCs",
            "allMACs": "Macs"
        },
        "computerListSpec": {
            "agentAvailability": "Agent Availability",
            "agentName": "Device Name",
            "machineModel": "Computer Type",
            "osPlatform": "OS Platform",
            "osVersion": "OS Version",
            "activeIpAddress": "IP Address",
            "currentUserName": "Current Username",
            "computerEsn": "ESN",
            "agentSerialNumber": "Agent Serial Number",
            "deviceFreezeStatus": "Device Freeze Status"
        },
        "computerItemAgentInformationSpec": {
            "agentActiveIp": "Agent Active IP",
            "agentVersion": "Agent Version",
            "agentBuildNumber": "Agent Build Number",
            "agentSerialNumber": "Agent Serial Number",
            "computerOnline": "Computer Online",
            "machineModel": "Machine Model",
            "osPlatform": "OS Platform",
            "osVersion": "OS Version",
            "sdServerAddress": "SD Server Address",
            "lmServerAddress": "LM Server Address",
            "sdServerCheckInterval": "SD Server Check Interval",
            "lmServerCheckInterval": "LM Server Check Interval",
            "includedInOsPatchManagement": "Included in OS Patch Management",
            "includedInThirdPartyPatchManagement": "Included in Third-Party Patch Management",
            "useOnlyAbsoluteManageForOsUpdates": "Use Only Absolute Manage for OS Updates",
            "absoluteRemoteEnabled": "Absolute Remote Enabled",
            "absoluteRemotePort": "Absolute Remote Port",
            "absoluteRemoteUserConfirmationRequired": "Absolute Remote User Confirmation Required",
            "computerOwnership": "Computer Ownership",
            "computerEnrollmentDate": "Computer Enrollment Date",
            "computerEnrolledInMdm": "Computer Enrolled in MDM",
            "computerEnrolledViaEnrollmentProgram": "Computer Enrolled via Enrollment Program",
            "computerEnrollmentProgramRegistrationDate": "Computer Enrollment Program Registration Date",
            "computerEnrollmentProfileAssignmentDate": "Computer Enrollment Profile Assignment Date",
            "computerEnrollmentProfileInstallationDate": "Computer Enrollment Profile Installation Date",
            "computerEnrollmentProfileUuid": "Computer Enrollment Profile UUID",
            "computerEnrollmentStatus": "Computer Enrollment Status",
            "computerDeviceIdentifierUdid": "Computer Device Identifier (UDID)",
            "computerIsTracked": "Computer Is Tracked",
            "lastHeartbeat": "Last Heartbeat",
            "recordCreationDate": "Record Creation Date",
            "clientInformation1": "Client Information 1",
            "clientInformation2": "Client Information 2",
            "clientInformation3": "Client Information 3",
            "clientInformation4": "Client Information 4",
            "clientInformation5": "Client Information 5",
            "clientInformation6": "Client Information 6",
            "clientInformation7": "Client Information 7",
            "clientInformation8": "Client Information 8",
            "clientInformation9": "Client Information 9",
            "clientInformation10": "Client Information 10",
            "computerManufacturer": "Computer Manufacturer"
        },
        "computerCpuSpec": {
            "osPlatform": "OS Platform",
            "processorType": "Processor Type",
            "processorVendor": "Processor Vendor",
            "processorSpeed": "Processor Speed",
            "busSpeed": "Bus Speed",
            "physicalCores": "Physical Cores",
            "activeCores": "Active Cores",
            "coresPerProcessor": "Cores per Processor",
            "processorL1DataCache": "Processor L1 Data Cache",
            "processorL1InformationCache": "Processor L1 Instruction Cache",
            "processorL2DataCache": "Processor L2 Data Cache",
            "processorL2InstructionCache": "Processor L2 Instruction Cache",
            "processorL3Cache": "Processor L3 Cache",
            "processorSupportsHyperthreading": "Processor Supports Hyperthreading",
            "processorHyperthreadingEnabled": "Processor Hyperthreading Enabled",
            "processorHasMMX": "Processor Has MMX",
            "processorHas3dNow": "Processor Has 3DNow",
            "processorHasSSE": "Processor Has SSE",
            "processorHasSSE2": "Processor Has SSE2",
            "processorHasSSE3": "Processor Has SSE3",
            "processorFamily": "Processor Family",
            "processorModel": "Processor Model",
            "processorStepping": "Processor Stepping"
        },
        "computerHardwareTabSpec": {
            "computerSerialNumber": "Computer Serial Number",
            "primaryMacAddress": "Primary MAC Address",
            "dateTime": "Date & Time",
            "bootRomInformation": "Boot ROM Information",
            "memorySlots": "Memory Slots",
            "memoryModuleCount": "Memory Module Count",
            "physicalMemory": "Physical Memory",
            "swapSpaceTotal": "Swap Space Total",
            "swapSpaceUsed": "Swap Space Used",
            "swapSpaceFree": "Swap Space Free",
            "swapSpaceEncrypted": "Swap Space Encrypted",
            "biosData": "BIOS Date",
            "biosVendor": "BIOS Vendor",
            "biosVersion": "BIOS Version",
            "biosType": "BIOS Type",
            "smbiosVersion": "SMBIOS Version",
            "mainboardManufacturer": "Mainboard Manufacturer",
            "mainboardProductName": "Mainboard Product Name",
            "mainboardSerialNumber": "Mainboard Serial Number",
            "mainboardType": "Mainboard Type",
            "mainboardVersion": "Mainboard Version",
            "mainboardAssetTag": "Mainboard Asset Tag",
            "systemEnclosureManufacturer": "System Enclosure Manufacturer",
            "systemEnclosureSerialNumber": "System Enclosure Serial Number",
            "systemEnclosureType": "System Enclosure Type",
            "systemEnclosureVersion": "System Enclosure Version",
            "systemEnclosureAssetTag": "System Enclosure Asset Tag",
            "computerManufacturer": "Computer Manufacturer",
            "computerVersion": "Computer Version",
            "computerModel": "Computer Model",
            "computerServiceTag": "Computer Service Tag",
            "computerWarrantyInfo": "Computer Warranty Info",
            "computerWarrantyEnd": "Computer Warranty End",
            "volumeCount": "Volume Count",
            "ataDeviceCount": "ATA Device Count",
            "scsiDeviceCount": "SCSI Device Count",
            "fireWireDeviceCount": "FireWire Device Count",
            "usbDeviceCount": "USB Device Count",
            "pciDeviceCount": "PCI Device Count",
            "displayCount": "Display Count",
            "computerType": "Computer Type",
            "smcVersion": "SMC Version",
            "computerAge": "Computer Age",
            "computerProductionDate": "Computer Production Date",
            "computerProductionFactory": "Computer Production Factory",
            "appleProductName": "Apple Product Name",
            "applePurchaseDate": "Computer Purchase Date",
            "appleWarrantyInfo": "Computer Warranty Info",
            "appleWarrantyEnd": "Computer Warranty End"
        },
        "computerInstalledProfileSpec": {
            "profileDisplayName": "Installed Profile Name",
            "profileType": "Installed Profile Type",
            "profileIdentifier": "Installed Profile Identifier",
            "profileInstallDate": "Installed Profile Installation Date",
            "profileOrganization": "Installed Profile Organization",
            "profileUninstallPolicy": "Installed Profile Allow Removal",
            "profileUser": "Installed Profile For User",
            "profileVerificationState": "Installed Profile Verification State",
            "profileDescription": "Installed Profile Description"
        },
        "computerInstalledSoftwareSpec": {
            "instSoftwareName": "Inst. Software Name",
            "instSoftwareVersionString": "Inst. Software Version String",
            "instSoftwareSize": "Inst. Software Size",
            "instSoftwareInstallationDate": "Inst. Software Installation Date",
            "identificationType": "Identification Type",
            "instSoftwareProductId": "Inst. Software Product ID",
            "instSoftwareCompany": "Inst. Software Company",
            "uninstallable": "Uninstallable",
            "isHotfix": "Is Hotfix",
            "installLocation": "Install Location",
            "registeredCompany": "Registered Company",
            "registeredOwner": "Registered Owner",
            "installedBy": "Installed By",
            "instSoftwareInfo": "Inst. Software Info"
        },
        "computerMemorySpec": {
            "memorySlotName": "Memory Slot Name",
            "memorySize": "Memory Size",
            "memorySpeed": "Memory Speed",
            "memoryType": "Memory Type"
        },
        "computerMissingPathSpec": {
            "missingPatchName": "Missing Patch Name",
            "missingPatchIsMandatory": "Missing Patch Is Mandatory",
            "missingPatchReleaseDate": "Missing Patch Release Date",
            "missingPatchAction": "Missing Patch Action",
            "missingPatchInstallDeadline": "Missing Patch Install Deadline",
            "missingPatchLanguage": "Missing Patch Language",
            "missingPatchVersion": "Missing Patch Version",
            "missingPatchSeverity": "Missing Patch Severity",
            "missingPatchIsOsPatch": "Missing Patch Is OS Patch"
        },
        "computerNetworkAdapterSpec": {
            "adapterName": "Adapter Name",
            "adapterIpAddress": "Adapter IP Address",
            "adapterSubnetMask": "Adapter Subnet Mask",
            "adapterMacAddress": "Adapter MAC Address",
            "configurationType": "Configuration Type",
            "primaryInterface": "Primary Interface",
            "routerAddress": "Router Address",
            "dhcpServerAddress": "DHCP Server Address",
            "dnsServers": "DNS Servers",
            "searchDomains": "Search Domains",
            "tcpImplementation": "TCP Implementation",
            "deviceName": "Device Name",
            "linkStatus": "Link Status",
            "adapterSpeed": "Adapter Speed",
            "fullDuplex": "Full Duplex",
            "adapterVendor": "Adapter Vendor",
            "hardware": "Hardware"
        },
        "computerSystemSoftwareSpec": {
            "osPlatform": "OS Platform",
            "osVersion": "OS Version",
            "osBuildNumber": "OS Build Number",
            "osLanguage": "OS Language",
            "computerBootTime": "Computer Boot Time",
            "computerUpTime": "Computer Uptime",
            "currentUserName": "Current User Name",
            "currentUserAccount": "Current User Account",
            "currentUserIsAdmin": "Current User Is Admin",
            "lastUserAccount": "Last User Account",
            "lastUserName": "Last User Name",
            "adComputerName": "AD Computer Name",
            "adComputerOrganizationalUnit": "AD Computer Organizational Unit",
            "adComputerOrganizationalUnitPath": "AD Computer Organizational Unit Path",
            "adUserOrganizationalUnit": "AD User Organizational Unit",
            "adUserOrganizationalUnitPath": "AD User Organizational Unit Path",
            "diskEncryptionProduct": "Disk Encryption Product",
            "diskEncryptionVersion": "Disk Encryption Version",
            "diskEncryptionStatus": "Disk Encryption Status",
            "diskEncryptionAlgorithm": "Disk Encryption Algorithm",
            "diskEncryptionKeySize": "Disk Encryption Key Size",
            "fileVaultSupported": "FileVault Supported",
            "fileVaultEnabled": "FileVault Enabled",
            "fileVaultAuthenticatedRestartSupported": "FileVault Authenticated Restart Supported",
            "fileVaultHasPersonalRecoveryKey": "FileVault Has Personal Recovery Key",
            "fileVaultHasInstitutionalRecoveryKey": "FileVault Has Institutional Recovery Key",
            "fileVaultUnlockedUsingRecoveryKey": "FileVault Unlocked Using Recovery Key",
            "fileVaultRecoveryKeyStoredOnServer": "FileVault Recovery Key Stored on Server",
            "gmtDelta": "GMT Delta",
            "daylightSavingTime": "Daylight-Saving Time",
            "fastUserSwitchingEnabled": "Fast User Switching Enabled",
            "firewallEnabled": "Firewall Enabled",
            "installedSoftwareCount": "Installed Software Count",
            "missingOsPatchesCount": "Missing OS Patches Count",
            "processCount": "Process Count",
            "fileCount": "File Count",
            "fontCount": "Font Count",
            "printerCount": "Printer Count",
            "timbuktuAccess": "Timbuktu Access",
            "vncAccess": "VNC Access",
            "networkAdapterCount": "Network Adapter Count",
            "absoluteRemoteEnabled": "Absolute Remote Enabled",
            "remoteDesktopScreenSharing": "Remote Desktop Screen Sharing",
            "osServicePack": "OS Service Pack",
            "osInstallationDate": "OS Installation Date",
            "osActivated": "OS Activated",
            "osActivationGracePeriod": "OS Activation Grace Period",
            "osSerialNumber": "OS Serial Number",
            "osProductId": "OS Product ID",
            "osIsVolumeLicensed": "OS Is Volume-Licensed",
            "virtualMachine": "Virtual Machine",
            "securityIdentifier": "Security Identifier",
            "osSoftwareUpdatesEnabled": "OS Update Utility Enabled",
            "allowRemoteAssistance": "Allow Remote Assistance",
            "allowRemoteControlViaAssistance": "Allow Remote Control via Assistance",
            "pcAnywhereAccess": "PC Anywhere Access",
            "damewareAccess": "DameWare Access",
            "defenderInstalled": "Defender Installed",
            "defenderEnabled": "Defender Enabled",
            "defenderRealTimeProtection": "Defender Real-Time Protection",
            "defenderAutoScanEnabled": "Defender Auto Scan Enabled",
            "defenderEngineVersion": "Defender Engine Version",
            "defenderDefinitionVersion": "Defender Definition Version",
            "windowsServiceCount": "Windows Service Count",
            "darwinVersion": "Darwin Version",
            "personalFileSharing": "Personal File Sharing",
            "windowsFileSharing": "Windows File Sharing",
            "personalWebSharing": "Personal Web Sharing",
            "remoteLogin": "Remote Login",
            "ftpAccess": "FTP Access",
            "remoteAppleEvents": "Remote Apple Events",
            "printerSharing": "Printer Sharing",
            "remoteManagement": "Remote Management",
            "wakeOnLanEnabled": "Wake on LAN Enabled",
            "wakeOnLanSupported": "Wake on LAN Supported",
            "osUpdateUtilityEnabled": "OS Update Utility Enabled",
            "startupItemCount": "Startup Item Count"
        },
        "computerVolumeSpec": {
            "volumeName": "Volume Name",
            "size": "Size",
            "format": "Format",
            "freeSpace": "Free Space",
            "freeSpacePercent": "Free Space %",
            "bootVolume": "Boot Volume",
            "compressed": "Compressed",
            "displayName": "Display Name",
            "driveLetter": "Drive Letter",
            "volumeSerialNumber": "Volume Serial Number",
            "volumeType": "Volume Type",
            "objectCount": "Object Count",
            "folderCount": "Folder Count",
            "journaled": "Journaled",
            "lockedByHardware": "Locked by Hardware",
            "lockedBySoftware": "Locked by Software"
        },
        "customFieldsStore": {
            "name": "Name",
            "description": "Description",
            "dataType": "Data Type"
        },
        "customFieldsDataTypeStore": {
            "string": "String",
            "number": "Number",
            "boolean": "Boolean",
            "date": "Date",
            "fileVersion": "File Version",
            "ipAddress": "IP Address",
            "enumeration": "Enumeration"
        },
        "customFieldsFormatAsStore": {
            "decimal": "Decimal",
            "decimalNoSeparators": "Decimal no separators",
            "bytes": "Bytes"
        },
        "customFieldsEnumerationListStore": {
            "name": "Values"
        },
        "mobileDeviceCustomFieldStore": {
            "information": "Name",
            "data": "Value",
            "dataType": "Data Type",
            "description": "Description"
        }
    }
},
  "ja": true,
});