define({
  "amData": {
    "policyFromActionSpec": {
        "policyName": "ポリシー名",
        "repeatCount": "リピート数",
        "repeatInterval": "リピート間隔",
        "initialDelay": "初期遅延"
    },
    "mobileDeviceSpec": {
        "name": "デバイス名",
        "model": "モデル",
        "osVersion": "OS バージョン",
        "serialNumber": "シリアル番号",
        "lastContact": "最終アクセス日時",
        "osPlatform": "OS タイプ",
        "isManaged": "管理中",
        "absoluteAppsVersion": "AbsoluteApps のバージョン",
        "dataRoamingEnabled": "データローミングが有効",
        "voiceRoamingEnabled": "音声ローミングが有効",
        "isPasscodePresent": "パスコードあり",
        "cellularTechnology": "携帯電話技術",
        "osBuildNumber": "OS ビルド番号",
        "isGpsCapable": "GPS 対応",
        "isJailBroken": "Jailbreak された",
        "isMdmProfileUpToDate": "MDM プロファイルが最新",
        "isTablet": "タブレット",
        "isPasscodeCompliant": "パスコードの準拠",
        "isPasscodeCompliantWithProfiles": "パスコードのプロファイルとの準拠"
    },
    "commandGroupStore": {
        "computerLabel": "コンピューター",
        "mobileDeviceLabel": "モバイルデバイス"
    },
    "commandMobileQueueSpec": {
        "command": "コマンド",
        "deviceName": "デバイス名",
        "deviceModel": "デバイスモデル",
        "osVersion": "OS バージョン",
        "status": "ステータス",
        "timeIssued": "発行した時間"
    },
    "commandMobileHistorySpec": {
        "command": "コマンド",
        "deviceName": "デバイス名",
        "deviceModel": "デバイスモデル",
        "osVersion": "OS バージョン",
        "timeIssued": "発行した時間",
        "timeFinished": "終了した時間",
        "commandError": "コマンドエラー",
        "commandErrorInfo": "コマンドエラー情報"
    },
    "commandComputerQueueSpec": {
        "status": "コマンドステータス",
        "statusNumber": "ステータス番号",
        "commandName": "コマンド",
        "commandUUID": "コマンド UUID",
        "administratorName": "アドミニストレーター名",
        "computerEsn": "ESN",
        "agentName": "デバイス名",
        "scheduledTime": "スケジュールした時刻"
    },
    "commandComputerHistorySpec": {
        "status": "コマンドステータス",
        "statusNumber": "ステータス番号",
        "commandName": "コマンド",
        "commandUUID": "コマンド UUID",
        "administratorName": "アドミニストレーター名",
        "computerEsn": "ESN",
        "agentName": "デバイス名",
        "startTime": "開始時刻",
        "commandError": "コマンドエラー",
        "commandErrorInfo": "コマンドエラー情報"
    },
    "mobilePolicySpec": {
        "name": "ポリシー名",
        "isSmartPolicy": "スマートポリシー",
        "guid": "GUID",
        "unmanagedDevices": "管理外のデバイス"
    },
    "thirdPartyApplicationsFromPolicySpec": {
        "icon": "アイコン",
        "name": "アプリ名",
        "osPlatform": "OS",
        "category": "カテゴリ",
        "minOsVersion": "互換性",
        "shortDescription": "簡略説明",
        "longDescription": "詳細説明",
        "appStoreURL": "アプリストアのウェブページ",
        "isUniversal": "ユニバーサル",
        "supportedDevices": "サポートされているデバイス",
        "preventDataBackup": "データバックアップの阻止",
        "removeWhenMDMIsRemoved": "MDM が削除されたら削除",
        "hasRedemptionCode": "回収コードあり",
        "vppCodesPurchased": "購入済み VPP",
        "vppCodesRedeemed": "引換済み VPP",
        "vppCodesRemaining": "残余 VPP",
        "assignmentRule": "ルール"
    },
    "mobileDeviceAssignedApsSpec": {
        "icon": "アイコン",
        "appName": "アプリ名",
        "policyName": "ポリシー名",
        "rule": "ルール"
    },
    "mobileDeviceInstalledApplicationSpec": {
        "name": "アプリ名",
        "versionString": "バージョン文字列",
        "buildNumber": "ビルド番号",
        "bundleIdentifier": "バンドル識別子",
        "packageName": "パッケージ名",
        "appSize": "アプリサイズ",
        "appStatus": "アプリステータス",
        "dataSize": "アプリデータサイズ",
        "preventDataBackup": "データバックアップの阻止",
        "boundToMDM": "MDM にバウンド",
        "appInstallDirectory": "インストール済みのアプリデータディレクトリ"
    },
    "inHouseApplicationFromPolicySpec": {
        "name": "アプリ名",
        "osPlatform": "OS タイプ",
        "version": "バージョン",
        "buildNumber": "ビルド番号",
        "size": "サイズ",
        "shortDescription": "簡略説明",
        "longDescription": "詳細説明",
        "bundleIdentifier": "バンドル識別子",
        "packageName": "パッケージ名",
        "minOsVersion": "互換性",
        "isUniversal": "ユニバーサル",
        "supportedDevices": "サポートされているデバイス",
        "provisioningProfile": "iOS プロビジョニングプロファイル名",
        "provProfileExpiryDate": "iOS プロビジョニングプロファイル有効期限",
        "assignmentRule": "ルール"
    },
    "mobilePolicyAssignedApsSpec": {
        "appName": "アプリ名",
        "policyName": "ポリシー名",
        "rule": "ルール"
    },
    "contentToMobilePolicyAssignmentSpec": {
        "policyName": "ポリシー名",
        "isSmartPolicy": "スマートポリシー",
        "mediaFileAssignmentType": "割り当てルール",
        "mediaFileAssignmentAvailability": "可用性",
        "mediaFileAssignmentStartTime": "開始時刻",
        "mediaFileAssignmentEndTime": "終了時刻"
    },
    "mobileDeviceInstalledConfigurationProfileSpec": {
        "name": "プロファイル名",
        "description": "説明",
        "organization": "発行組織",
        "profileType": "プロファイルのタイプ",
        "identifier": "プロファイル識別子",
        "uuid": "プロフィール UUID",
        "isEncrypted": "暗号化されたプロファイル",
        "isManaged": "管理されたプロファイル",
        "allowRemoval": "削除を許可"
    },
    "configurationProfileFromPolicySpec": {
        "name": "プロファイル名",
        "description": "説明",
        "organization": "発行組織",
        "osPlatform": "OS タイプ",
        "profileType": "プロファイルのタイプ",
        "identifier": "プロファイル識別子",
        "uuid": "プロフィール UUID",
        "allowRemoval": "削除を許可",
        "variablesUsed": "使用された変数",
        "availabilitySelector": "可用性",
        "profileStartTime": "開始時刻",
        "profileEndTime": "終了時刻",
        "assignmentRule": "割り当てルール"
    },
    "mobileDeviceAssignedProfilesSpec": {
        "profileName": "プロファイル名",
        "policyName": "ポリシー名",
        "availabilitySelector": "可用性",
        "profileStartTime": "開始時刻",
        "profileEndTime": "終了時刻"
    },
    "administratorSpec": {
        "administratorName": "アドミニストレーター名"
    },
    "certificateSpec": {
        "name": "証明書の名前",
        "isIdentity": "識別子の証明書"
    },
    "installedProvisioningProfileSpec": {
        "uuid": "UUID",
        "name": "プロファイル名",
        "expiry": "プロファイル有効期限"
    },
    "performedActionsSpec": {
        "name": "名前",
        "description": "説明",
        "policyName": "ポリシー名",
        "type": "タイプ",
        "executionTime": "実行時刻"
    },
    "contentSpec": {
        "name": "名前",
        "description": "説明",
        "mediaFileName": "ファイル名",
        "type": "タイプ",
        "mediaCategory": "メディアカテゴリ",
        "modified": "最終更新日",
        "mediaFileSize": "ファイルのサイズ",
        "wifiOnly": "Wi-Fi のみ",
        "canLeaveAbsSafe": "AbsoluteSafe から出ることができる",
        "canBeEmailed": "メール送信可能",
        "canBePrinted": "印刷可能",
        "hashedPassword": "ハッシュ化されたパスワード"
    },
    "inHouseApplicationSpec": {
        "name": "アプリ名",
        "osPlatform": "OS タイプ",
        "version": "バージョン",
        "buildNumber": "ビルド番号",
        "size": "サイズ",
        "shortDescription": "簡略説明",
        "longDescription": "詳細説明",
        "bundleIdentifier": "バンドル識別子",
        "packageName": "パッケージ名",
        "minOsVersion": "互換性",
        "isUniversal": "ユニバーサル",
        "supportedDevices": "サポートされているデバイス",
        "provisioningProfile": "iOS プロビジョニングプロファイル名",
        "provProfileExpiryDate": "iOS プロビジョニングプロファイル有効期限"
    },
    "thirdPartyApplicationsSpec": {
        "icon": "アイコン",
        "name": "アプリ名",
        "osPlatform": "OS",
        "category": "カテゴリ",
        "minOsVersion": "互換性",
        "shortDescription": "簡略説明",
        "longDescription": "詳細説明",
        "appStoreURL": "アプリストアのウェブページ",
        "isUniversal": "ユニバーサル",
        "supportedDevices": "サポートされているデバイス",
        "preventDataBackup": "データバックアップの阻止",
        "removeWhenMDMIsRemoved": "MDM が削除されたら削除",
        "hasRedemptionCode": "回収コードあり",
        "vppCodesPurchased": "購入済み VPP",
        "vppCodesRedeemed": "引換済み VPP",
        "vppCodesRemaining": "残余 VPP",
        "assignmentRule": "ルール"
    },
    "assignableBookstoreBookSpec": {
        "name": "タイトル",
        "category": "カテゴリ",
        "shortDescription": "簡略説明",
        "icon": "アイコン"
    },
    "configurationProfileSpec": {
        "name": "プロファイル名",
        "description": "説明",
        "organization": "発行組織",
        "osPlatform": "OS タイプ",
        "profileType": "プロファイルのタイプ",
        "identifier": "プロファイル識別子",
        "uuid": "プロフィール UUID",
        "allowRemoval": "削除を許可",
        "variablesUsed": "使用された変数"
    },
    "provisioningProfileSpec": {
        "name": "プロファイル名",
        "expiry": "プロファイル有効期限",
        "uuid": "UUID"
    },
    "actionsSpec": {
        "name": "アクション名",
        "type": "アクションタイプ",
        "description": "アクションの説明",
        "osPlatform": "アクションでサポートされるプラットフォーム",
        "lastModified": "最終更新日"
    },
    "mobileDeviceFromMobilePolicySpec": {
        "name": "名前",
        "model": "モデル",
        "osVersion": "OS バージョン",
        "serialNumber": "シリアル番号",
        "phoneNumber": "電話番号",
        "lastContact": {
            "value": "最終アクセス日時",
            "comment": "JA - last accessed date and time"
        },
        "simIccId": "SIM ICC 識別子",
        "imei": "IMEI",
        "osPlatform": "OS タイプ",
        "osBuildNumber": "OS ビルド番号"
    },
    "mobileDeviceGroupStore": {
        "allMobileDevices": "すべてのモバイルデバイス",
        "allAndroidDevices": "すべての Android デバイス",
        "allAndroidTablets": "すべての Android タブレット",
        "allAndroidPhones": "すべての Android フォン",
        "alliOSDevices": "すべての iOS デバイス",
        "alliPhones": "すべての iPhone",
        "alliPads": "すべての iPad",
        "alliPodTouchDevices": "すべての iPod Touch デバイス",
        "allWindowsPhoneDevices": "すべての Windows Phone デバイス"
    },
    "assignableItemMenuStore": {
        "content": "コンテンツ",
        "inHouseApplications": "インハウスアプリケーション",
        "thirdPartyApplications": "サードパーティアプリケーション",
        "bookstoreBooks": "ブックストアのブック",
        "configurationProfiles": "構成プロファイル",
        "provisioningProfiles": "プロビジョニングプロファイル",
        "actions": "アクション"
    },
    "computerGroupStore": {
        "allComputers": "すべてのコンピューター",
        "allPCs": "PC",
        "allMACs": "MAC"
    },
    "computerListSpec": {
        "agentAvailability": "エージェントの可用性",
        "agentName": "デバイス名",
        "machineModel": "コンピュータータイプ",
        "osPlatform": "OS プラットフォーム",
        "osVersion": "OS バージョン",
        "activeIpAddress": "IP アドレス",
        "currentUserName": "現在のユーザー名",
        "computerEsn": "ESN",
        "agentSerialNumber": "エージェントのシリアル番号",
        "deviceFreezeStatus": "デバイスフリーズステータス"
    },
    "computerItemAgentInformationSpec": {
        "agentActiveIp": "エージェントのアクティブ IP",
        "agentVersion": "エージェントバージョン",
        "agentBuildNumber": "エージェントのビルド番号",
        "agentSerialNumber": "エージェントのシリアル番号",
        "computerOnline": "コンピューターオンライン",
        "machineModel": "マシンモデル",
        "osPlatform": "OS プラットフォーム",
        "osVersion": "OS バージョン",
        "sdServerAddress": "SD サーバーアドレス",
        "lmServerAddress": "LM サーバーアドレス",
        "sdServerCheckInterval": "SD サーバーチェック間隔",
        "lmServerCheckInterval": "LM サーバーチェック間隔",
        "includedInOsPatchManagement": "OS パッチ管理に含まれる",
        "includedInThirdPartyPatchManagement": "サードパーティパッチ管理に含まれる",
        "useOnlyAbsoluteManageForOsUpdates": "OS のアップデートには Absolute Manage のみ使用",
        "absoluteRemoteEnabled": "Absolute Remote が有効",
        "absoluteRemotePort": "Absolute Remote ポート",
        "absoluteRemoteUserConfirmationRequired": "Absolute Remote のユーザー確認が必要",
        "computerOwnership": "コンピューターのオーナーシップ",
        "computerEnrollmentDate": "コンピューターの登録日",
        "computerEnrolledInMdm": "コンピューターが MDM に登録済み",
        "computerEnrolledViaEnrollmentProgram": "コンピューターが登録プログラムを通じて登録済み",
        "computerEnrollmentProgramRegistrationDate": "コンピューター登録プログラムの登録日",
        "computerEnrollmentProfileAssignmentDate": "コンピューター登録プロファイルの割り当て日",
        "computerEnrollmentProfileInstallationDate": "コンピューター登録プロファイルのインストール日",
        "computerEnrollmentProfileUuid": "コンピューター登録プロファイルの UUID",
        "computerEnrollmentStatus": "コンピューター登録ステータス",
        "computerDeviceIdentifierUdid": "コンピューターのデバイス識別子 (UDID)",
        "computerIsTracked": "コンピューターを追跡中",
        "lastHeartbeat": "最終ハートビート",
        "recordCreationDate": "記録作成日",
        "clientInformation1": "クライアント情報 1",
        "clientInformation2": "クライアント情報 2",
        "clientInformation3": "クライアント情報 3",
        "clientInformation4": "クライアント情報 4",
        "clientInformation5": "クライアント情報 5",
        "clientInformation6": "クライアント情報 6",
        "clientInformation7": "クライアント情報 7",
        "clientInformation8": "クライアント情報 8",
        "clientInformation9": "クライアント情報 9",
        "clientInformation10": "クライアント情報 10",
        "computerManufacturer": "コンピューターの製造業者"
    },
    "computerCpuSpec": {
        "osPlatform": "OS プラットフォーム",
        "processorType": "プロセッサーのタイプ",
        "processorVendor": "プロセッサーのベンダー",
        "processorSpeed": "プロセッサーの速度",
        "busSpeed": "バスの速度",
        "physicalCores": "物理コア",
        "activeCores": "アクティブコア",
        "coresPerProcessor": "プロセッサー当たりのコア",
        "processorL1DataCache": "プロセッサー L1 データキャッシュ",
        "processorL1InformationCache": "プロセッサー L1 インストラクションキャッシュ",
        "processorL2DataCache": "プロセッサー L2 データキャッシュ",
        "processorL2InstructionCache": "プロセッサー L2 インストラクションキャッシュ",
        "processorL3Cache": "プロセッサー L3 キャッシュ",
        "processorSupportsHyperthreading": "プロセッサーはハイパースレッディングをサポート",
        "processorHyperthreadingEnabled": "プロセッサーのハイパースレッディングが有効",
        "processorHasMMX": "プロセッサーに MMX あり",
        "processorHas3dNow": "プロセッサーに 3DNow あり",
        "processorHasSSE": "プロセッサーに SSE あり",
        "processorHasSSE2": "プロセッサーに SSE2 あり",
        "processorHasSSE3": "プロセッサーに SSE3 あり",
        "processorFamily": "プロセッサーファミリー",
        "processorModel": "プロセッサーのモデル",
        "processorStepping": "プロセッサーのステッピング"
    },
    "computerHardwareTabSpec": {
        "computerSerialNumber": "コンピューターのシリアル番号",
        "primaryMacAddress": "プライマリ MAC アドレス",
        "dateTime": "日時",
        "bootRomInformation": "ROM 起動情報",
        "memorySlots": "メモリースロット",
        "memoryModuleCount": "メモリーモジュール数",
        "physicalMemory": "物理メモリー",
        "swapSpaceTotal": "合計スワップ領域",
        "swapSpaceUsed": "使用済みスワップ領域",
        "swapSpaceFree": "空きスワップ領域",
        "swapSpaceEncrypted": "暗号化済みスワップ領域",
        "biosData": "BIOS 日付",
        "biosVendor": "BIOS ベンダー",
        "biosVersion": "BIOS バージョン",
        "biosType": "BIOS タイプ",
        "smbiosVersion": "SMBIOS バージョン",
        "mainboardManufacturer": "メインボード製造業者",
        "mainboardProductName": "メインボード製品名",
        "mainboardSerialNumber": "メインボードのシリアル番号",
        "mainboardType": "メインボードのタイプ",
        "mainboardVersion": "メインボードのバージョン",
        "mainboardAssetTag": "メインボードのアセットタグ",
        "systemEnclosureManufacturer": "システムエンクロージャー製造業者",
        "systemEnclosureSerialNumber": "システムエンクロージャーのシリアル番号",
        "systemEnclosureType": "システムエンクロージャーのタイプ",
        "systemEnclosureVersion": "システムエンクロージャーのバージョン",
        "systemEnclosureAssetTag": "システムエンクロージャーのアセットタグ",
        "computerManufacturer": "コンピューターの製造業者",
        "computerVersion": "コンピューターのバージョン",
        "computerModel": "コンピューターのモデル",
        "computerServiceTag": "コンピューターのサービスタグ",
        "computerWarrantyInfo": "コンピューターの保証情報",
        "computerWarrantyEnd": "コンピューターの保証終了",
        "volumeCount": "ボリューム数",
        "ataDeviceCount": "ATA デバイス数",
        "scsiDeviceCount": "SCSI デバイス数",
        "fireWireDeviceCount": "FireWire デバイス数",
        "usbDeviceCount": "USB デバイス数",
        "pciDeviceCount": "PCI デバイス数",
        "displayCount": "数を表示",
        "computerType": "コンピュータータイプ",
        "smcVersion": "SMC バージョン",
        "computerAge": "コンピューターの製造年数",
        "computerProductionDate": "コンピューターの製造日",
        "computerProductionFactory": "コンピューターの製造工場",
        "appleProductName": "Apple 製品名",
        "applePurchaseDate": "コンピューターの購入日",
        "appleWarrantyInfo": "コンピューターの保証情報",
        "appleWarrantyEnd": "コンピューターの保証終了"
    },
    "computerInstalledProfileSpec": {
        "profileDisplayName": "インストール済みプロファイルの名前",
        "profileType": "インストール済みプロファイルのタイプ",
        "profileIdentifier": "インストール済みプロファイルの識別子",
        "profileInstallDate": "インストール済みプロファイルのインストール日",
        "profileOrganization": "インストール済みプロファイルの組織",
        "profileUninstallPolicy": "インストール済みのプロファイルが削除を許可",
        "profileUser": "ユーザー向けインストール済みプロファイル",
        "profileVerificationState": "インストール済みプロファイルの検証状態",
        "profileDescription": "インストール済みプロファイルの説明"
    },
    "computerInstalledSoftwareSpec": {
        "instSoftwareName": "インストール済みソフトウェアの名前",
        "instSoftwareVersionString": "インストール済みソフトウェアのバージョン文字列",
        "instSoftwareSize": "インストール済みソフトウェアのサイズ",
        "instSoftwareInstallationDate": "インストール済みソフトウェアのインストール日",
        "identificationType": "識別タイプ",
        "instSoftwareProductId": "インストール済みソフトウェアの製品 ID",
        "instSoftwareCompany": "インストール済みソフトウェアの会社",
        "uninstallable": "インストール不可",
        "isHotfix": "ホットフィックス",
        "installLocation": "インストール場所",
        "registeredCompany": "登録会社",
        "registeredOwner": "登録オーナー",
        "installedBy": "インストール実行者",
        "instSoftwareInfo": "インストール済みソフトウェアの情報"
    },
    "computerMemorySpec": {
        "memorySlotName": "メモリースロットの名前",
        "memorySize": "メモリーのサイズ",
        "memorySpeed": "メモリーの速度",
        "memoryType": "メモリーのタイプ"
    },
    "computerMissingPathSpec": {
        "missingPatchName": "不足しているパッチの名前",
        "missingPatchIsMandatory": "不足しているパッチは必須である",
        "missingPatchReleaseDate": "不足しているパッチのリリース日",
        "missingPatchAction": "不足しているパッチのアクション",
        "missingPatchInstallDeadline": "不足しているパッチのインストール期日",
        "missingPatchLanguage": "不足しているパッチの言語",
        "missingPatchVersion": "不足しているパッチのバージョン",
        "missingPatchSeverity": "不足しているパッチの重要度",
        "missingPatchIsOsPatch": "不足しているパッチは OS パッチです"
    },
    "computerNetworkAdapterSpec": {
        "adapterName": "アダプターの名前",
        "adapterIpAddress": "アダプターの IP アドレス",
        "adapterSubnetMask": "アダプターのサブネットマスク",
        "adapterMacAddress": "アダプターの MAC アドレス",
        "configurationType": "構成タイプ",
        "primaryInterface": "プライマリーインターフェイス",
        "routerAddress": "ルーターアドレス",
        "dhcpServerAddress": "DHCP サーバーアドレス",
        "dnsServers": "DNS サーバー",
        "searchDomains": "検索ドメイン",
        "tcpImplementation": "TCP 実装",
        "deviceName": "デバイス名",
        "linkStatus": "リンクステータス",
        "adapterSpeed": "アダプターの速度",
        "fullDuplex": "全二重",
        "adapterVendor": "アダプターのベンダー",
        "hardware": "ハードウェア"
    },
    "computerSystemSoftwareSpec": {
        "osPlatform": "OS プラットフォーム",
        "osVersion": "OS バージョン",
        "osBuildNumber": "OS ビルド番号",
        "osLanguage": "OS の言語",
        "computerBootTime": "コンピューターの起動時間",
        "computerUpTime": "コンピューターのアップタイム",
        "currentUserName": "現在のユーザー名",
        "currentUserAccount": "現在のユーザーアカウント",
        "currentUserIsAdmin": "現在のユーザーは管理者です",
        "lastUserAccount": "最後のユーザーアカウント",
        "lastUserName": "最後のユーザー名",
        "adComputerName": "AD コンピュータの名前",
        "adComputerOrganizationalUnit": "AD コンピューターの組織単位",
        "adComputerOrganizationalUnitPath": "AD コンピューターの組織単位パス",
        "adUserOrganizationalUnit": "AD ユーザーの組織単位",
        "adUserOrganizationalUnitPath": "AD ユーザーの組織単位パス",
        "diskEncryptionProduct": "ディスク暗号化製品",
        "diskEncryptionVersion": "ディスク暗号化バージョン",
        "diskEncryptionStatus": "ディスク暗号化ステータス",
        "diskEncryptionAlgorithm": "ディスク暗号化アルゴリズム",
        "diskEncryptionKeySize": "ディスク暗号化キーのサイズ",
        "fileVaultSupported": "FileVault をサポート",
        "fileVaultEnabled": "FileVault が有効",
        "fileVaultAuthenticatedRestartSupported": "FileVault の認証による再起動をサポート",
        "fileVaultHasPersonalRecoveryKey": "FileVault にパーソナルリカバリーキーがある",
        "fileVaultHasInstitutionalRecoveryKey": "FileVault に組織リカバリーキーがある",
        "fileVaultUnlockedUsingRecoveryKey": "FileVault がリカバリーキーを使用してアンロックされました",
        "fileVaultRecoveryKeyStoredOnServer": "サーバーに保存された FileVault リカバリーキー",
        "gmtDelta": "GMT デルタ",
        "daylightSavingTime": "夏時間",
        "fastUserSwitchingEnabled": "ユーザーの高速切り替えが有効",
        "firewallEnabled": "ファイアウォールが有効",
        "installedSoftwareCount": "インストール済みソフトウェアの数",
        "missingOsPatchesCount": "不足している OS パッチの数",
        "processCount": "プロセス数",
        "fileCount": "ファイル数",
        "fontCount": "フォント数",
        "printerCount": "プリンター数",
        "timbuktuAccess": "Timbuktu アクセス",
        "vncAccess": "VNC アクセス",
        "networkAdapterCount": "ネットワーク アダプター数",
        "absoluteRemoteEnabled": "Absolute Remote が有効",
        "remoteDesktopScreenSharing": "リモートデスクトップ画面共有",
        "osServicePack": "OS サービスパック",
        "osInstallationDate": "OS インストール日",
        "osActivated": "アクティブ化した OS",
        "osActivationGracePeriod": "OS アクティベーション猶予期間",
        "osSerialNumber": "OS シリアル番号",
        "osProductId": "OS 製品 ID",
        "osIsVolumeLicensed": "OS がボリュームライセンス契約である",
        "virtualMachine": "仮想マシン",
        "securityIdentifier": "セキュリティ識別子",
        "osSoftwareUpdatesEnabled": "OS 更新ユーティリティが有効",
        "allowRemoteAssistance": "リモートアシスタンスを許可",
        "allowRemoteControlViaAssistance": "アシスタンスによるリモートコントロールを許可",
        "pcAnywhereAccess": "PC Anywhere Access",
        "damewareAccess": "DameWare アクセス",
        "defenderInstalled": "Defender をインストール済み",
        "defenderEnabled": "Defender が有効",
        "defenderRealTimeProtection": "Defender リアルタイム保護",
        "defenderAutoScanEnabled": "Defender オートスキャンが有効",
        "defenderEngineVersion": "Defender エンジンバージョン",
        "defenderDefinitionVersion": "Defender 定義バージョン",
        "windowsServiceCount": "Windows サービス数",
        "darwinVersion": "Darwin バージョン",
        "personalFileSharing": "個人ファイル共有",
        "windowsFileSharing": "Windows ファイル共有",
        "personalWebSharing": "個人ウェブ共有",
        "remoteLogin": "遠隔ログイン",
        "ftpAccess": "FTP アクセス",
        "remoteAppleEvents": "遠隔 Apple イベント",
        "printerSharing": "プリンター共有",
        "remoteManagement": "遠隔管理",
        "wakeOnLanEnabled": "Wake on LAN が有効",
        "wakeOnLanSupported": "Wake on LAN をサポート",
        "osUpdateUtilityEnabled": "OS 更新ユーティリティが有効",
        "startupItemCount": "スタートアップアイテム数"
    },
    "computerVolumeSpec": {
        "volumeName": "ボリューム名",
        "size": "サイズ",
        "format": "フォーマット",
        "freeSpace": "空き領域",
        "freeSpacePercent": "空き領域の割合（%）",
        "bootVolume": "起動ボリューム",
        "compressed": "圧縮",
        "displayName": "ディスプレイ名",
        "driveLetter": "ドライブレター",
        "volumeSerialNumber": "ボリュームシリアル番号",
        "volumeType": "ボリュームタイプ",
        "objectCount": "オブジェクト数",
        "folderCount": "フォルダ数",
        "journaled": "ジャーナリング",
        "lockedByHardware": "ハードウェアによるロック",
        "lockedBySoftware": "ソフトウェアによるロック"
    },
    "customFieldsStore": {
        "name": "名前",
        "description": "説明",
        "dataType": "データ型"
    },
    "customFieldsDataTypeStore": {
        "string": "文字列",
        "number": "数値",
        "boolean": "Boolean",
        "date": "日付",
        "fileVersion": "ファイルバージョン",
        "ipAddress": "IP アドレス",
        "enumeration": "数え上げ"
    },
    "customFieldsFormatAsStore": {
        "decimal": "10進法",
        "decimalNoSeparators": "10進法 (区切り記号なし)",
        "bytes": "バイト"
    },
    "customFieldsEnumerationListStore": {
        "name": "値"
    },
    "mobileDeviceCustomFieldStore": {
        "information": "名前",
        "data": "値",
        "dataType": "データ型",
        "description": "説明"
    }
},
});