#define login_landing_page 1000
#define	mobile_devices_page	1001
#define mobile_device_details_page 1002
#define	lock_device_dialog 1003
#define	clear_passcode_dialog 1004
#define	set_passcode_dialog	1005
#define	delete_data_dialog 1006
#define	send_message_dialog	1007
#define	set_device_name_dialog 1008
#define	set_roaming_options_dialog 1009
#define	install_application_dialog 1010
#define	install_configuration_profile_dialog 1011
#define	install_provisioning_profile_dialog	1012
#define	set_device_ownership_dialog	1013
#define	set_device_enrollment_user_dialog 1014
#define	set_organizational_info_dialog 1015
#define	set_activation_lock_options_dialog 1016
#define	retry_all_dialog 1017
#define	queued_commands_page 1018
#define	command_history_page 1019
#define	mobile_policies_page 1020
#define	delete_policy_dialog 1021
#define	edit_mobile_policy_dialog 1022
#define	edit_smart_mobile_policy_dialog	1023
#define	create_a_mobile_policy_dialog 1024
#define	create_a_mobile_smart_policy_dialog	1025
#define	mobile_policy_details_page 1026
#define	add_mobile_devices_to_policy_dialog	1027
#define	add_in-house_applications_dialog 1028
#define	add_third-party_applications_dialog	1029
#define	add_configuration_profile_dialog 1030
#define	add_content_to_this_policy_dialog 1031
#define	assignable_content_page	1032
#define	add_new_mobile_content_dialog 1033
#define	assignable_content_details_page	1034
#define	edit_content_dialog	1035
#define	delete_content_dialog 1036
#define	add_this_content_to_policies_dialog	1037
#define	assignable_in-house_apps_page 1038
#define	assignable_third-party_apps_page 1039
#define	assignable_bookstore_books_page	1040
#define	assignable_configuration_profiles_page 1041
#define	assignable_provisioning_profiles_page 1042
#define edit_assignment_properties_dialog 1043
#define show_hide_columns_dialog 1044
#define computers_page 1051
#define send_message_dialog_computers 1052
#define gather_inventory_dialog 1053
#define computer_details_page 1054
#define assignable_actions_page 1055
#define delete_action_dialog 1056
#define duplicate_action_dialog 1057
#define send_message_to_device_action_dialogs 1058
#define send_email_action_dialogs 1059
#define send_sms_action_dialogs 1060
#define set_roaming_options_action_dialogs 1061
#define set_activation_lock_options_action_dialogs 1062
#define set_wallpaper_action_dialogs 1063
#define set_device_name_action_dialogs 1064
#define set_custom_field_value_action_dialogs 1065
#define update_device_informaton_action_dialogs 1066
#define set_attention_mode_action_dialogs 1067
#define freeze_device_action_dialogs 1068
#define register_user_in_vpp_action_dialogs 1069
#define retire_user_from_vpp_action_dialogs 1070
#define remove_configuration_profile_action_dialogs 1071
#define demote_to_unmanaged_device_action_dialogs 1072
#define assignable_action_details_page 1073
#define add_action_to_policies_dialog 1074
#define custom_information_fields_page 1075
#define delete_custom_information_fields_dialog 1076
#define create_custom_information_field_dialog 1077
#define add_action_to_policy_dialog 1078
#define edit_custom_information_field_dialog 1081
#define duplicate_custom_information_field_dialog 1080
#define edit_custom_field_value_dialog 1079
#define send_vpp_invitation_action_dialogs 1082
